/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#d2bbff",
        "primary-fixed": "#eaddff",
        "on-primary-container": "#ede0ff",
        "on-tertiary-fixed-variant": "#713700",
        "primary": "#d2bbff",
        "surface-container-lowest": "#100d16",
        "primary-container": "#7c3aed",
        "surface-bright": "#3c3742",
        "on-tertiary": "#4f2500",
        "on-surface": "#e8dfee",
        "tertiary-fixed": "#ffdcc6",
        "on-secondary-fixed": "#001f26",
        "on-secondary": "#003640",
        "surface": "#15121b",
        "on-tertiary-container": "#ffe0cd",
        "inverse-on-surface": "#332f39",
        "surface-variant": "#37333e",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-high": "#2c2833",
        "secondary-container": "#03b5d3",
        "tertiary-fixed-dim": "#ffb784",
        "on-error": "#690005",
        "secondary": "#4cd7f6",
        "inverse-primary": "#732ee4",
        "on-tertiary-fixed": "#301400",
        "error-container": "#93000a",
        "surface-dim": "#15121b",
        "surface-container-low": "#1d1a24",
        "outline-variant": "#4a4455",
        "on-error-container": "#ffdad6",
        "on-primary": "#3f008e",
        "surface-container": "#221e28",
        "on-surface-variant": "#ccc3d8",
        "on-background": "#e8dfee",
        "tertiary-container": "#a15100",
        "tertiary": "#ffb784",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-container": "#00424e",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#d2bbff",
        "outline": "#958da1",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary-fixed": "#25005a",
        "secondary-fixed": "#acedff",
        "surface-container-highest": "#37333e",
        "inverse-surface": "#e8dfee",
        "background": "#15121b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "container-max": "1280px",
        "stack-md": "24px",
        "unit": "8px",
        "stack-sm": "12px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "mono-sm": ["Geist", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "mono-sm": ["12px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
